// pages/_app.tsx
import { withAuthenticator } from '@aws-amplify/ui-react';
import { Amplify } from 'aws-amplify';
import config from '@/amplifyconfiguration.json';
import '@aws-amplify/ui-react/styles.css';
import { AppProps } from 'next/app';
import RootLayout from './layout';

// configure the Amplify client library with the configuration generated by `amplify sandbox`
Amplify.configure(config);

function App({ Component, pageProps}: AppProps) {
  return (<RootLayout>
    <div>
      <Component {...pageProps} />
    </div>
    </RootLayout>)
}

export default withAuthenticator(App);